package io.o2mc.sdk.current.business;

import java.util.ArrayList;
import java.util.List;

import io.o2mc.sdk.current.domain.Event;

/**
 * Holds all events generated by user interaction from the app implementing our SDK.
 */
public class EventBus {
    private List<Event> events;

    public EventBus() {
        events = new ArrayList<>();
    }

    public void add(Event e) {
        events.add(e);
    }
}
