package io.o2mc.sdk.business;

import android.util.Log;

import java.util.ArrayList;
import java.util.List;

import io.o2mc.sdk.domain.Event;

/**
 * Holds all events generated by user interaction from the app implementing our SDK.
 */
public class EventBus {

    private static final String TAG = "EventBus";

    private List<Event> events;

    public EventBus() {
        events = new ArrayList<>();
    }

    public void add(Event e) {
        Log.d(TAG, String.format("Added event '%s' to EventBus.", e.getName()));
        events.add(e);
    }

    public List<Event> getEvents() {
        return events;
    }

    public void clearEvents() {
        events.clear();
        Log.d(TAG, "clearEvents: Cleared the EventBus.");
    }
}
