package io.o2mc.sdk.business.event;

import android.util.Log;

import java.util.ArrayList;
import java.util.List;

import io.o2mc.sdk.BuildConfig;
import io.o2mc.sdk.domain.Event;
import io.o2mc.sdk.util.TimeUtil;

/**
 * Holds all events generated by user interaction from the app implementing our SDK.
 */
public class EventBus {

    private static final String TAG = "EventBus";

    private final List<Event> events;

    public EventBus() {
        events = new ArrayList<>();
    }

    public void add(Event e) {
        if (BuildConfig.DEBUG)
            Log.d(TAG, String.format("Added event '%s' to EventBus.", e.getName()));

        events.add(e);
    }

    public List<Event> getEvents() {
        return events;
    }

    public void clearEvents() {
        events.clear();

        if (BuildConfig.DEBUG)
            Log.d(TAG, "clearEvents: Cleared the EventBus.");
    }

    public Event generateEvent(String eventName) {
        if (BuildConfig.DEBUG)
            Log.i(TAG, String.format("generateEvent: Generated event with name '%s'", eventName));

        return new Event(eventName, null, TimeUtil.generateTimestamp());
    }

    public Event generateEventWithProperties(String eventName, String value) {
        if (BuildConfig.DEBUG)
            Log.i(TAG, String.format("generateEventWithProperties: Generated event '%s' with value consisting of '%s' characters", eventName, value.length()));

        return new Event(eventName, value, TimeUtil.generateTimestamp());
    }
}
