package io.o2mc.sdk.business.event;

import io.o2mc.sdk.domain.Event;
import io.o2mc.sdk.util.TimeUtil;
import java.util.ArrayList;
import java.util.List;

/**
 * Holds all events generated by user interaction from the app implementing our SDK.
 */
public class EventBus {

  private final List<Event> events;

  public EventBus() {
    events = new ArrayList<>();
  }

  public void add(Event e) {
    events.add(e);
  }

  public List<Event> getEvents() {
    return events;
  }

  public void clearEvents() {
    events.clear();
  }

  public Event generateEvent(String eventName) {
    return new Event(eventName, null, TimeUtil.generateTimestamp());
  }

  public Event generateEventWithProperties(String eventName, Object value) {
    return new Event(eventName, value, TimeUtil.generateTimestamp());
  }
}
